import { sanitizeLabel, sanitizeWordList } from './content-utils.js';

export const CAMPAIGN_MAX_LEVEL = 100;

const RAW_CAMPAIGN_LEVELS = [
    { id: 1, theme: 'Animais domésticos', gridSize: 8, wordCount: 5, allowedDirections: ['horizontal'], words: ['GATO', 'CAO', 'COELHO', 'HAMSTER', 'PEIXE', 'PASSARO', 'PATO', 'RATO', 'BURRO', 'PONEI'] },
    { id: 2, theme: 'Frutas', gridSize: 8, wordCount: 5, allowedDirections: ['horizontal'], words: ['UVA', 'PERA', 'MACA', 'BANANA', 'MANGA', 'MELAO', 'LIMAO', 'KIWI', 'CAJU', 'FIGO'] },
    { id: 3, theme: 'Cores', gridSize: 8, wordCount: 5, allowedDirections: ['horizontal'], words: ['AZUL', 'VERDE', 'ROSA', 'PRETO', 'BRANCO', 'CINZA', 'ROXO', 'BEGE', 'LILAS', 'OURO'] },
    { id: 4, theme: 'Partes do corpo', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal'], words: ['MAO', 'PE', 'OLHO', 'BOCA', 'NARIZ', 'ORELHA', 'BRACO', 'PERNA', 'DEDO', 'CABECA'] },
    { id: 5, theme: 'Objetos da casa', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal'], words: ['MESA', 'SOFA', 'CAMA', 'PORTA', 'JANELA', 'TAPETE', 'VASO', 'QUADRO', 'ABAJUR', 'CHAVE'] },
    { id: 6, theme: 'Comidas simples', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal'], words: ['ARROZ', 'FEIJAO', 'PAO', 'BOLO', 'SOPA', 'OVO', 'QUEIJO', 'MASSA', 'SALADA', 'FRANGO'] },
    { id: 7, theme: 'Profissões', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal'], words: ['MEDICO', 'PROF', 'JUIZ', 'ATOR', 'GARCOM', 'PILOTO', 'PINTOR', 'POLICIA', 'PADEIRO', 'DENTISTA'] },
    { id: 8, theme: 'Roupas', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal'], words: ['CAMISA', 'CALCA', 'SAIA', 'VESTIDO', 'MEIA', 'TENIS', 'BONE', 'LUVA', 'CASACO', 'CINTO'] },
    { id: 9, theme: 'Brinquedos', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal'], words: ['BOLA', 'BONECA', 'CARRINHO', 'PIAO', 'DOMINO', 'DADO', 'URSO', 'PIPA', 'IOIO', 'BLOCOS'] },
    { id: 10, theme: 'Escola', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal'], words: ['LAPIS', 'CANETA', 'CADERNO', 'LIVRO', 'MOCHILA', 'REGUA', 'GIZ', 'PROVA', 'AULA', 'CLASSE'], event: 'Primeira conquista' },
    { id: 11, theme: 'Bebidas', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal', 'vertical'], words: ['AGUA', 'SUCO', 'LEITE', 'CAFE', 'CHA', 'REFRI', 'VITAMINA', 'CACAU', 'MATE', 'SODA'] },
    { id: 12, theme: 'Natureza básica', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal', 'vertical'], words: ['ARVORE', 'FLOR', 'RIO', 'LAGO', 'MAR', 'SOL', 'LUA', 'VENTO', 'PEDRA', 'TERRA'] },
    { id: 13, theme: 'Transporte', gridSize: 8, wordCount: 6, allowedDirections: ['horizontal', 'vertical'], words: ['CARRO', 'ONIBUS', 'TREM', 'METRO', 'AVIAO', 'BARCO', 'MOTO', 'BIKE', 'TAXI', 'VAN'] },
    { id: 14, theme: 'Animais da fazenda', gridSize: 8, wordCount: 7, allowedDirections: ['horizontal', 'vertical'], words: ['VACA', 'PORCO', 'GALINHA', 'CAVALO', 'CABRA', 'OVELHA', 'PATO', 'GANSO', 'BURRO', 'TOURO'] },
    { id: 15, theme: 'Utensílios de cozinha', gridSize: 8, wordCount: 7, allowedDirections: ['horizontal', 'vertical'], words: ['COPO', 'PRATO', 'GARFO', 'FACA', 'COLHER', 'PANELA', 'JARRA', 'TIGELA', 'FORMA', 'RALADOR'] },
    { id: 16, theme: 'Dias da semana', gridSize: 8, wordCount: 7, allowedDirections: ['horizontal', 'vertical'], words: ['DOMINGO', 'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO'] },
    { id: 17, theme: 'Clima', gridSize: 8, wordCount: 7, allowedDirections: ['horizontal', 'vertical'], words: ['CHUVA', 'SOL', 'VENTO', 'NUBLADO', 'FRIO', 'CALOR', 'NEVE', 'RAIO', 'GELO', 'BRISA'] },
    { id: 18, theme: 'Lugares da cidade', gridSize: 8, wordCount: 7, allowedDirections: ['horizontal', 'vertical'], words: ['RUA', 'PRACA', 'BANCO', 'LOJA', 'ESCOLA', 'HOSPITAL', 'MERCADO', 'PARQUE', 'IGREJA', 'PONTE'] },
    { id: 19, theme: 'Esportes populares', gridSize: 10, wordCount: 6, allowedDirections: ['horizontal', 'vertical'], words: ['FUTEBOL', 'VOLEI', 'TENIS', 'GOLF', 'SURF', 'SKATE', 'BOXE', 'JUDO', 'XADREZ', 'CORRIDA'] },
    { id: 20, theme: 'Família', gridSize: 10, wordCount: 6, allowedDirections: ['horizontal', 'vertical'], words: ['MAE', 'PAI', 'FILHO', 'FILHA', 'AVO', 'NETO', 'TIO', 'TIA', 'PRIMO', 'IRMAO'] },
    { id: 21, theme: 'Países', gridSize: 10, wordCount: 6, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['BRASIL', 'CHILE', 'PERU', 'CUBA', 'JAPAO', 'INDIA', 'ITALIA', 'FRANCA', 'CANADA', 'MEXICO'] },
    { id: 22, theme: 'Capitais', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['PARIS', 'ROMA', 'LISBOA', 'MADRI', 'LONDRES', 'BERLIM', 'TOKYO', 'LIMA', 'OSLO', 'DUBLIN'] },
    { id: 23, theme: 'Tecnologia básica', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['MOUSE', 'TELA', 'CHIP', 'PIXEL', 'DADOS', 'EMAIL', 'SENHA', 'LOGIN', 'SITE', 'APP'] },
    { id: 24, theme: 'Redes sociais', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['POST', 'LIKE', 'STORY', 'VIDEO', 'FOTO', 'REELS', 'CHAT', 'GRUPO', 'PERFIL', 'SEGUIR'] },
    { id: 25, theme: 'Filmes', gridSize: 10, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['MATRIX', 'AVATAR', 'TITANIC', 'ROCKY', 'ALIEN', 'SHREK', 'FROZEN', 'MOANA', 'BATMAN', 'BARBIE'], event: 'Cine Challenge' },
    { id: 26, theme: 'Séries', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['EPISODIO', 'TEMPORADA', 'CENA', 'ATOR', 'ATRIZ', 'DRAMA', 'COMEDIA', 'FINAL', 'PILOTO', 'ELENCO'] },
    { id: 27, theme: 'Música', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['ROCK', 'POP', 'JAZZ', 'SAMBA', 'FUNK', 'RAP', 'BLUES', 'CORO', 'RITMO', 'NOTA'] },
    { id: 28, theme: 'Instrumentos', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['VIOLAO', 'PIANO', 'FLAUTA', 'BATERIA', 'BAIXO', 'HARPA', 'TAMBOR', 'SAX', 'GAITA', 'VIOLINO'] },
    { id: 29, theme: 'Jogos', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['TETRIS', 'PACMAN', 'MARIO', 'SONIC', 'ZELDA', 'ROBLOX', 'FIFA', 'SIMS', 'XADREZ', 'DOMINO'] },
    { id: 30, theme: 'Marcas famosas', gridSize: 10, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['APPLE', 'GOOGLE', 'AMAZON', 'TESLA', 'NIKE', 'ADIDAS', 'SONY', 'NOKIA', 'CANON', 'LEGO'] },
    { id: 31, theme: 'Comida internacional', gridSize: 10, wordCount: 6, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['PIZZA', 'SUSHI', 'TACO', 'RAMEN', 'PAELLA', 'CURRY', 'KEBAB', 'PASTA', 'RISOTO', 'WAFFLE', 'NACHOS', 'QUICHE'] },
    { id: 32, theme: 'Restaurantes', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['MENU', 'MESA', 'GARCOM', 'PEDIDO', 'PRATO', 'CONTA', 'CHEFE', 'COZINHA', 'SABOR', 'RESERVA', 'BUFFET', 'GORJETA'] },
    { id: 33, theme: 'Férias', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['VIAGEM', 'MALA', 'HOTEL', 'PASSEIO', 'ROTA', 'MAPA', 'TURISMO', 'PRAIA', 'FERIAS', 'GUIA', 'TICKET', 'AVIAO'] },
    { id: 34, theme: 'Praia', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['AREIA', 'MAR', 'ONDA', 'SOL', 'CONCHA', 'ILHA', 'COCO', 'SURF', 'BRISA', 'TOALHA', 'BARCO', 'CORAL'] },
    { id: 35, theme: 'Montanha', gridSize: 10, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['PICO', 'TRILHA', 'VALE', 'PEDRA', 'NEVE', 'RIO', 'LAGO', 'CABANA', 'ALTURA', 'BOSQUE', 'CUME', 'ALPES'] },
    { id: 36, theme: 'Animais selvagens', gridSize: 10, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['LEAO', 'TIGRE', 'ZEBRA', 'GIRAFA', 'PANDA', 'JACARE', 'COBRA', 'LOBO', 'RAPOSA', 'MACACO', 'GORILA', 'ANTA'] },
    { id: 37, theme: 'Aves', gridSize: 10, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['AGUIA', 'ARARA', 'TUCANO', 'CORUJA', 'FALCAO', 'GAVIAO', 'PATO', 'GARCA', 'CISNE', 'POMBO', 'EMA', 'PAVAO'] },
    { id: 38, theme: 'Peixes', gridSize: 10, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['PEIXE', 'TUBARAO', 'BALEIA', 'ORCA', 'POLVO', 'LULA', 'SIRI', 'FOCA', 'SALMAO', 'TRUTA', 'CARPA', 'ATUM'] },
    { id: 39, theme: 'Insetos', gridSize: 10, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['ABELHA', 'FORMIGA', 'MOSCA', 'BESOURO', 'GRILO', 'CUPIM', 'PULGA', 'TRACA', 'VESPA', 'BARATA', 'LIBELULA', 'LAGARTA'] },
    { id: 40, theme: 'Flores', gridSize: 10, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['ROSA', 'LIRIO', 'TULIPA', 'JASMIM', 'CRAVO', 'MARGARIDA', 'ORQUIDEA', 'VIOLETA', 'GIRASSOL', 'HORTA', 'PETALA', 'CAULE'] },
    { id: 41, theme: 'Emoções', gridSize: 12, wordCount: 7, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['ALEGRIA', 'MEDO', 'RAIVA', 'CALMA', 'AMOR', 'SAUDADE', 'SURPRESA', 'NOJO', 'CULPA', 'PAZ', 'FOCO', 'ANIMO'] },
    { id: 42, theme: 'Qualidades humanas', gridSize: 12, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['CORAGEM', 'BONDADE', 'PACIENCIA', 'HONRA', 'CALMA', 'HUMOR', 'FORCA', 'CUIDADO', 'RESPEITO', 'EMPATIA', 'FOCO', 'TATO'] },
    { id: 43, theme: 'Verbos comuns', gridSize: 12, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['CORRER', 'ANDAR', 'OLHAR', 'PENSAR', 'FALAR', 'OUVIR', 'SENTIR', 'CRIAR', 'APRENDER', 'BUSCAR', 'ACHAR', 'VIVER'] },
    { id: 44, theme: 'Adjetivos', gridSize: 12, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['BONITO', 'RAPIDO', 'LENTO', 'CLARO', 'ESCURO', 'SUAVE', 'FORTE', 'LEVE', 'DOCE', 'SIMPLES', 'RICO', 'NOVO'] },
    { id: 45, theme: 'Sentimentos positivos', gridSize: 12, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['PAZ', 'AMOR', 'CALMA', 'GRATIDAO', 'ESPERANCA', 'LUZ', 'SORRISO', 'ABRACO', 'BONDADE', 'HUMOR', 'FOCO', 'ANIMO'], event: 'Mind Level' },
    { id: 46, theme: 'Sentimentos negativos', gridSize: 12, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['MEDO', 'RAIVA', 'CULPA', 'TRISTEZA', 'DUVIDA', 'ANSIA', 'SOLIDAO', 'INVEJA', 'DOR', 'CANSAco', 'PERDA', 'TENSO'] },
    { id: 47, theme: 'Palavras difíceis', gridSize: 12, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['ENIGMA', 'PARADOXO', 'ABSTRATO', 'SUTIL', 'RARO', 'COMPLEXO', 'NUANCE', 'ECO', 'ZENITE', 'ORIGEM', 'SIMBOLO', 'VETOR'] },
    { id: 48, theme: 'Sinônimos', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['FELIZ', 'ALEGRE', 'CALMO', 'SERENO', 'RAPIDO', 'VELOZ', 'BELO', 'BONITO', 'FORTE', 'FIRME', 'CLARO', 'LIMPO'] },
    { id: 49, theme: 'Antônimos', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['CLARO', 'ESCURO', 'ALTO', 'BAIXO', 'FORTE', 'FRACO', 'DOCE', 'AMARGO', 'QUENTE', 'FRIO', 'LEVE', 'PESADO'] },
    { id: 50, theme: 'Filosofia básica', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['IDEIA', 'RAZAO', 'ETICA', 'LOGICA', 'MENTE', 'SER', 'TEMPO', 'CAUSA', 'VALOR', 'MORAL', 'VERDADE', 'DUVIDA'], event: 'Halfway' },
    { id: 51, theme: 'Universo', gridSize: 12, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['SOL', 'LUA', 'TERRA', 'MARTE', 'ESTRELA', 'GALAXIA', 'COMETA', 'COSMOS', 'ORBITA', 'ESPACO', 'NAVE', 'ASTRO'] },
    { id: 52, theme: 'Planetas', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['MERCURIO', 'VENUS', 'TERRA', 'MARTE', 'JUPITER', 'SATURNO', 'URANO', 'NETUNO', 'PLUTAO', 'ORBITA', 'ANEL', 'LUA'] },
    { id: 53, theme: 'Astronomia', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['ECLIPSE', 'NEBULOSA', 'METEORO', 'COMETA', 'GALAXIA', 'ASTRO', 'TELESCOPIO', 'ORBITA', 'COSMOS', 'VACUO', 'LUZ', 'RADAR'] },
    { id: 54, theme: 'Ciência', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['ATOMO', 'CELULA', 'GENE', 'TESTE', 'DADO', 'ENERGIA', 'MASSA', 'FORCA', 'NERVOS', 'PLANTA', 'METODO', 'LABOR'] },
    { id: 55, theme: 'Química', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['ATOMO', 'ION', 'ACIDO', 'BASE', 'SAL', 'GAS', 'METAL', 'OXIDO', 'MOLECULA', 'CARBONO', 'HIDROGENIO', 'REACAO'] },
    { id: 56, theme: 'Física', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['FORCA', 'MASSA', 'LUZ', 'SOM', 'ONDA', 'CAMPO', 'ENERGIA', 'CALOR', 'VETOR', 'GRAVIDADE', 'RAIO', 'PESO'] },
    { id: 57, theme: 'Matemática', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['SOMA', 'CONTA', 'NUMERO', 'ANGULO', 'RAIZ', 'AREA', 'VOLUME', 'GRAFO', 'VETOR', 'MATRIZ', 'FATOR', 'LOGICA'] },
    { id: 58, theme: 'Números grandes', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['MILHAO', 'BILHAO', 'TRILHAO', 'CENTENA', 'DEZENA', 'DOBRO', 'METADE', 'ZERO', 'CEM', 'MIL', 'PAR', 'IMPAR'] },
    { id: 59, theme: 'Formas geométricas', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['CIRCULO', 'QUADRADO', 'TRIANGULO', 'CUBO', 'LINHA', 'PONTO', 'CONE', 'ESFERA', 'PRISMA', 'OVAL', 'ARCO', 'RETA'] },
    { id: 60, theme: 'Cores avançadas', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal'], words: ['TURQUESA', 'MAGENTA', 'VIOLETA', 'LILAS', 'DOURADO', 'PRATA', 'INDIGO', 'OCRE', 'RUBI', 'JADE', 'MARFIM', 'CORAL'] },
    { id: 61, theme: 'Mitologia grega', gridSize: 12, wordCount: 8, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['ZEUS', 'HERA', 'ARES', 'ATENA', 'APOLO', 'HERMES', 'HADES', 'POSEIDON', 'CRONOS', 'GAIA', 'EROS', 'NIX'] },
    { id: 62, theme: 'Mitologia nórdica', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['ODIN', 'THOR', 'LOKI', 'FREYA', 'BALDER', 'TYR', 'FRIGG', 'HEL', 'YMIR', 'FENRIR', 'RUNA', 'VALHALLA'] },
    { id: 63, theme: 'Heróis', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['HEROI', 'ESCUDO', 'CAPA', 'PODER', 'MISSAO', 'ALIADO', 'FORCA', 'CORAGEM', 'VITORIA', 'JUSTICA', 'SALVAR', 'LIDER'] },
    { id: 64, theme: 'Vilões', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['VILAO', 'SOMBRA', 'MEDO', 'PLANO', 'ARMADILHA', 'CAOS', 'PERIGO', 'FURIA', 'TRUQUE', 'ROUBO', 'CHEFE', 'RIVAL'] },
    { id: 65, theme: 'Fantasia', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['ELFO', 'FADA', 'ORC', 'MAGIA', 'REINO', 'ESPADA', 'DRAGAO', 'CASTELO', 'FEITIAO', 'BRUXA', 'MAGO', 'RUNAS'], event: 'Hero Stage' },
    { id: 66, theme: 'Magia', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['MAGO', 'VARINHA', 'FEITIAO', 'POCAO', 'ENCANTO', 'RUNA', 'PORTAL', 'CRISTAL', 'ORBE', 'ILUSAO', 'LUZ', 'SOMBRA'] },
    { id: 67, theme: 'Criaturas místicas', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['UNICORNIO', 'GRIFO', 'FENIX', 'SEREIA', 'DRAGAO', 'ELFO', 'GNOMO', 'TROLL', 'FADA', 'CICLOPE', 'MINOTAURO', 'PEGASO'] },
    { id: 68, theme: 'Dragões', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['DRAGAO', 'ASA', 'FOGO', 'ESCAMA', 'CAUDA', 'CAVERNA', 'TESOURO', 'OVO', 'CHAMA', 'GARRA', 'VIGIA', 'LENDAS'] },
    { id: 69, theme: 'Jogos RPG', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['CLASSE', 'MANA', 'QUEST', 'LOOT', 'BOSS', 'GUILDA', 'NIVEL', 'ARMA', 'MAGIA', 'DANO', 'CURA', 'MAPA'] },
    { id: 70, theme: 'Termos de batalha', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['ESPADA', 'ESCUDO', 'ARCO', 'FLECHA', 'LANCA', 'DUELO', 'ATAQUE', 'DEFESA', 'VITORIA', 'TATICA', 'FORCA', 'CERCO'] },
    { id: 71, theme: 'Estratégia', gridSize: 12, wordCount: 9, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['PLANO', 'TATICA', 'ROTA', 'RISCO', 'FOCO', 'META', 'ORDEM', 'DEFESA', 'ATAQUE', 'RECUO', 'AVANCO', 'MAPA'] },
    { id: 72, theme: 'Guerra', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['BATALHA', 'TROPA', 'BASE', 'CERCO', 'FRENTE', 'ARMAS', 'PAZ', 'TRINCHEIRA', 'GENERAL', 'ORDEM', 'ALIADO', 'MISSAO'] },
    { id: 73, theme: 'História antiga', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['ROMA', 'EGITO', 'GRECIA', 'IMPERIO', 'FARAO', 'CESAR', 'TEMPLO', 'PAPIRO', 'MUSEU', 'ANTIGO', 'TRONO', 'COROA'] },
    { id: 74, theme: 'Idade média', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['CASTELO', 'REI', 'RAINHA', 'CAVALEIRO', 'FEUDO', 'TORRE', 'MURALHA', 'TRONO', 'COROA', 'ESPADA', 'ESCUDO', 'VILA'] },
    { id: 75, theme: 'Civilizações', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['ROMA', 'EGITO', 'MAIA', 'INCA', 'GREGO', 'PERSA', 'AZTECA', 'SUMERIO', 'CHINA', 'INDIA', 'REINO', 'IMPERIO'], event: 'Expert' },
    { id: 76, theme: 'Reinos', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['REI', 'RAINHA', 'TRONO', 'COROA', 'CASTELO', 'REINO', 'LEI', 'GUARDA', 'NOBRE', 'VILA', 'TORRE', 'PACTO'] },
    { id: 77, theme: 'Liderança', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['LIDER', 'EQUIPE', 'META', 'FOCO', 'ORDEM', 'EXEMPLO', 'VISAO', 'PLANO', 'DECISAO', 'RESPEITO', 'VOZ', 'GUIA'] },
    { id: 78, theme: 'Política', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['VOTO', 'LEI', 'ESTADO', 'CAMARA', 'SENADO', 'PARTIDO', 'CARGO', 'PODER', 'GOVERNO', 'URNA', 'PACTO', 'REGRA'] },
    { id: 79, theme: 'Economia', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['MOEDA', 'BANCO', 'PRECO', 'VALOR', 'LUCRO', 'CUSTO', 'RENDA', 'JUROS', 'BOLSA', 'MERCADO', 'TAXA', 'SALDO'] },
    { id: 80, theme: 'Negócios', gridSize: 12, wordCount: 10, allowedDirections: ['horizontal', 'vertical', 'diagonal', 'reverse'], words: ['VENDA', 'MARCA', 'CLIENTE', 'LOJA', 'META', 'LUCRO', 'EQUIPE', 'PLANO', 'PRODUTO', 'SERVICO', 'CAIXA', 'GESTAO'] },
    { id: 81, theme: 'Arte', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['ARTE', 'TELA', 'TINTA', 'PINCEL', 'MUSEU', 'OBRA', 'LINHA', 'FORMA', 'LUZ', 'SOMBRA', 'COR', 'TRACO'] },
    { id: 82, theme: 'Pintura', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['TELA', 'OLEO', 'PINCEL', 'TINTA', 'COR', 'QUADRO', 'RETRATO', 'PALETA', 'FUNDO', 'ARTE', 'MURAL', 'TRACO'] },
    { id: 83, theme: 'Escultura', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['PEDRA', 'ARGILA', 'BRONZE', 'FORMA', 'VOLUME', 'ESTATUA', 'RELEVO', 'BASE', 'MOLDE', 'CINZEL', 'ARTE', 'MUSEU'] },
    { id: 84, theme: 'Arquitetura', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['PONTE', 'TORRE', 'CASA', 'PILAR', 'ARCO', 'PLANTA', 'FACHADA', 'CUPULA', 'PREDIO', 'OBRA', 'LINHA', 'VIGA'] },
    { id: 85, theme: 'Design', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['FORMA', 'LINHA', 'COR', 'GRADE', 'LOGO', 'ICONE', 'TELA', 'FONTE', 'MARCA', 'LAYOUT', 'ESBOCO', 'PADRAO'], event: 'Creative Mind' },
    { id: 86, theme: 'Literatura', gridSize: 12, wordCount: 9, allowedDirections: ['all'], words: ['LIVRO', 'POEMA', 'CONTO', 'ROMANCE', 'AUTOR', 'LEITOR', 'FRASE', 'PAGINA', 'CAPA', 'VERSO', 'DRAMA', 'PROSA'] },
    { id: 87, theme: 'Escritores', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['AUTOR', 'POETA', 'ROMANCISTA', 'CRITICO', 'LEITOR', 'OBRA', 'LIVRO', 'ENSAIO', 'CONTO', 'VERSO', 'PROSA', 'PENA'] },
    { id: 88, theme: 'Palavras raras', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['ZENITE', 'AUREO', 'SUTIL', 'EXIMIO', 'INEFAVEL', 'LUDICO', 'SERENO', 'VORAZ', 'TENAZ', 'PLENO', 'RARO', 'NUANCE'] },
    { id: 89, theme: 'Idiomas', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['INGLES', 'FRANCES', 'ESPANHOL', 'ITALIANO', 'ALEMAO', 'LATIM', 'GREGO', 'JAPONES', 'ARABE', 'CHINES', 'IDIOMA', 'FALA'] },
    { id: 90, theme: 'Cultura mundial', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['CULTURA', 'POVO', 'MUNDO', 'TRADICAO', 'IDIOMA', 'ARTE', 'DANCA', 'FESTA', 'CULTO', 'SIMBOLO', 'NACAO', 'ROTA'], event: 'World Master' },
    { id: 91, theme: 'Mistério', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['PISTA', 'SEGREDO', 'SOMBRA', 'ENIGMA', 'CHAVE', 'RUIDO', 'SINAL', 'CARTA', 'SUSPEITO', 'MISTERIO', 'CASO', 'MEDO'] },
    { id: 92, theme: 'Detetives', gridSize: 12, wordCount: 10, allowedDirections: ['all'], words: ['PISTA', 'LUPA', 'CASO', 'DETETIVE', 'PROVA', 'SINAL', 'CHAVE', 'ARQUIVO', 'MAPA', 'SUSPEITO', 'BUSCA', 'RELATO'] },
    { id: 93, theme: 'Crimes', gridSize: 12, wordCount: 11, allowedDirections: ['all'], words: ['CRIME', 'FURTO', 'ROUBO', 'PISTA', 'PROVA', 'CULPA', 'LEI', 'RISCO', 'CASO', 'ALARME', 'SOMBRA', 'PERITO'] },
    { id: 94, theme: 'Investigação', gridSize: 12, wordCount: 11, allowedDirections: ['all'], words: ['PROVA', 'PISTA', 'CASO', 'RELATO', 'BUSCA', 'ANALISE', 'PERITO', 'ARQUIVO', 'LOCAL', 'MAPA', 'SINAL', 'FOTO'] },
    { id: 95, theme: 'Psicologia', gridSize: 12, wordCount: 11, allowedDirections: ['all'], words: ['MENTE', 'EGO', 'SONHO', 'MEDO', 'FOCO', 'MEMORIA', 'TRAUMA', 'HABITO', 'DESEJO', 'RAZAO', 'EMOCAO', 'CALMA'] },
    { id: 96, theme: 'Inteligência', gridSize: 12, wordCount: 11, allowedDirections: ['all'], words: ['IDEIA', 'LOGICA', 'MEMORIA', 'FOCO', 'RAZAO', 'MENTE', 'TALENTO', 'ESTUDO', 'PADRAO', 'SINAL', 'ANALISE', 'SABER'] },
    { id: 97, theme: 'Lógica', gridSize: 12, wordCount: 12, allowedDirections: ['all'], words: ['LOGICA', 'RAZAO', 'PROVA', 'REGRA', 'PADRAO', 'SEQUENCIA', 'CAUSA', 'EFEITO', 'ORDEM', 'SINAL', 'MAPA', 'CHAVE'] },
    { id: 98, theme: 'Desafios mentais', gridSize: 12, wordCount: 12, allowedDirections: ['all'], words: ['ENIGMA', 'PUZZLE', 'PISTA', 'PADRAO', 'CHAVE', 'LOGICA', 'SEQUENCIA', 'CODIGO', 'MAPA', 'BUSCA', 'FOCO', 'MENTE'] },
    { id: 99, theme: 'Palavras complexas', gridSize: 12, wordCount: 12, allowedDirections: ['all'], words: ['PARADOXO', 'ABSTRATO', 'COMPLEXO', 'INEFAVEL', 'SIMBOLO', 'NUANCE', 'LOGICA', 'ENIGMA', 'SINTAXE', 'VETOR', 'ORIGEM', 'ZENITE'] },
    { id: 100, theme: 'Grande Final', gridSize: 12, wordCount: 12, allowedDirections: ['all'], words: ['FINAL', 'MESTRE', 'ENIGMA', 'VITORIA', 'JORNADA', 'CHAVE', 'SEGREDO', 'LOGICA', 'FOCO', 'CALMA', 'DESAFIO', 'PALAVRA'], event: 'Final Boss Puzzle' },
];

export const CAMPAIGN_LEVELS = RAW_CAMPAIGN_LEVELS.map((level) => ({
    ...level,
    theme: sanitizeLabel(level.theme),
    event: level.event ? sanitizeLabel(level.event) : undefined,
    words: sanitizeWordList(level.words, { minLength: 2 })
}));

export function getCampaignLevelConfig(levelId) {
    const id = Math.min(Math.max(Number(levelId) || 1, 1), CAMPAIGN_MAX_LEVEL);
    const level = CAMPAIGN_LEVELS[id - 1];
    const tier = id <= 10 ? 1 : id <= 30 ? 2 : id <= 60 ? 3 : id <= 85 ? 4 : 5;
    const isBoss = Boolean(level.event);
    return { ...level, levelId: id, tier, isBoss, seed: id * 12345, timeTargets: { three: 999999, two: 999999 } };
}

export function getCampaignWords(levelConfig) {
    return [...levelConfig.words].slice(0, levelConfig.wordCount);
}
